# Generated by Django 2.1.7 on 2021-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='Images/%Y/%m/%d')),
                ('Audio', models.FileField(blank=True, null=True, upload_to='Audio/%Y/%m/%d')),
                ('Video', models.FileField(blank=True, null=True, upload_to='Video/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(blank=True, editable=False, max_length=255, null=True, upload_to='Images/%Y/%m/%d')),
                ('Audio', models.FileField(blank=True, null=True, upload_to='Audio/%Y/%m/%d')),
                ('Video', models.FileField(blank=True, null=True, upload_to='Video/%Y/%m/%d')),
            ],
        ),
    ]
