# Generated by Django 2.1.7 on 2021-05-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfile',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='outputfile',
            name='Images',
        ),
    ]
