# Generated by Django 2.1.7 on 2021-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0003_auto_20210527_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfile',
            name='InFile',
        ),
        migrations.RemoveField(
            model_name='outputfile',
            name='OutFile',
        ),
        migrations.AddField(
            model_name='inputfile',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='Audio/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='outputfile',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='Audio/%Y/%m/%d'),
        ),
    ]
