# Generated by Django 2.1.7 on 2021-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0004_auto_20210527_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputfile',
            old_name='File',
            new_name='OutFile',
        ),
    ]
