# Generated by Django 2.1.7 on 2021-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0006_auto_20210527_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InFile', models.FileField(blank=True, null=True, upload_to='Input_File/%Y/%m/%d')),
                ('OutFile', models.FileField(blank=True, null=True, upload_to='OutPut_File/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='InputFile',
        ),
        migrations.DeleteModel(
            name='OutputFile',
        ),
    ]
