# Generated by Django 2.1.7 on 2021-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0007_auto_20210527_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='OutFile',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='OutPut_File/%Y/%m/%d'),
        ),
    ]
