# Generated by Django 2.1.7 on 2021-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0010_auto_20210527_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='OutFile',
            field=models.FileField(blank=True, null=True, upload_to='OutPut_File/%Y/%m/%d'),
        ),
    ]
